config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
    # add other controllers if needed
  }

  get '/home', to: 'home#home'
  get '/products', to: 'home#products'
  get '/dashboard', to: 'home#dashboard'
  get '/checkout', to: 'home#checkout'
  get '/cart', to: 'home#cart'
  get '/contact', to: 'home#contact'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#home'

  # Dashboard Routes
  get '/dashboard/sales', to: 'dashboards#sales', as: :dashboard_sales
  get '/dashboard/ecommerce', to: 'dashboards#ecommerce', as: :dashboard_ecommerce
  get '/dashboard/analytics', to: 'dashboards#analytics', as: :dashboard_analytics
  get '/dashboard/crm', to: 'dashboards#crm', as: :dashboard_crm
  get '/dashboard/project', to: 'dashboards#project', as: :dashboard_project
  get '/dashboard/search', to: 'dashboards#search', as: :dashboard_search

  # Discussions Routes
  get '/discussions/inbox', to: 'discussions#inbox', as: :discussions_inbox
  get '/discussions/chat', to: 'discussions#chat', as: :discussions_chat

  # Todos Routes
  get '/todos/lists', to: 'todos#lists', as: :todos_lists
  get '/todos/notes', to: 'todos#notes', as: :todos_notes

  # UI Components Routes
  get '/ui_components/ui_alerts', to: 'ui_components#ui_alerts', as: :ui_alerts
  get '/ui_components/ui_badges', to: 'ui_components#ui_badges', as: :ui_badges
  get '/ui_components/ui_buttons', to: 'ui_components#ui_buttons', as: :ui_buttons
  get '/ui_components/ui_cards', to: 'ui_components#ui_cards', as: :ui_cards
  get '/ui_components/ui_dropdowns', to: 'ui_components#ui_dropdowns', as: :ui_dropdowns
  get '/ui_components/ui_forms', to: 'ui_components#ui_forms', as: :ui_forms
  get '/ui_components/ui_list_groups', to: 'ui_components#ui_list_groups', as: :ui_list_groups
  get '/ui_components/ui_modals', to: 'ui_components#ui_modals', as: :ui_modals
  get '/ui_components/ui_progress_bars', to: 'ui_components#ui_progress_bars', as: :ui_progress_bars
  get '/ui_components/ui_tables', to: 'ui_components#ui_tables', as: :ui_tables
  get '/ui_components/ui_tabs', to: 'ui_components#ui_tabs', as: :ui_tabs
  get '/ui_components/feather_icons', to: 'ui_components#feather_icons', as: :feather_icons
  get '/ui_components/line_icons', to: 'ui_components#line_icons', as: :line_icons
  get '/ui_components/icofont_icons', to: 'ui_components#icofont_icons', as: :icofont_icons

  # Charts Routes
  get '/charts/line', to: 'charts#line', as: :charts_line
  get '/charts/area', to: 'charts#area', as: :charts_area
  get '/charts/column', to: 'charts#column', as: :charts_column
  get '/charts/bar', to: 'charts#bar', as: :charts_bar
  get '/charts/mixed', to: 'charts#mixed', as: :charts_mixed
  get '/charts/pie', to: 'charts#pie', as: :charts_pie

  # Pages Routes
  get 'pages/users_card', to: 'pages#users_card', as: :pages_users_card
  get 'pages/notifications', to: 'pages#notifications', as: :pages_notifications
  get 'pages/timeline', to: 'pages#timeline', as: :pages_timeline
  get 'pages/invoice_template', to: 'pages#invoice_template', as: :pages_invoice_template
  get 'pages/gallery', to: 'pages#gallery', as: :pages_gallery
  get 'pages/faq', to: 'pages#faq', as: :pages_faq
  get 'pages/pricing', to: 'pages#pricing', as: :pages_pricing
  get 'pages/profile', to: 'pages#profile', as: :pages_profile
  get 'pages/profile_settings', to: 'pages#profile_settings', as: :pages_profile_settings
  get 'pages/error', to: 'pages#error', as: :pages_error

  # Auth Routes
  get 'auth/signup', to: 'auth#signup', as: :auth_signup
  get 'auth/signin', to: 'auth#signin', as: :auth_signin
  get 'auth/forgot_password', to: 'auth#forgot_password', as: :auth_forgot_password

end

app/models/user.rb
# frozen_string_literal: true

# USER
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :profile_image
  has_one :personal_detail, as: :bio
  has_one_attached :avatar
  accepts_nested_attributes_for :personal_detail
  # after_create :full_name_set
  # after_update :full_name_set

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    super_admin: 0,
    admin: 1,
    customer: 2
  }, _prefix: true

  validates :email, format: { with: Devise.email_regexp }

  attr_accessor :limit

  def self.filter_role(current_user)
    if current_user.role_super_admin?
      %w[admin staff]
    else
      ['staff']
    end
  end

  def self.to_csv
    attributes = all.column_names
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |user|
        csv << attributes.map { |attr| user.send(attr) }
      end
    end
  end

  def full_name_set
    full_name = personal_detail.first_name + ' ' + personal_detail.last_name
    personal_detail.update_columns(full_name: full_name)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users
class UsersController < ApplicationController
  include ImportExport

  before_action :authenticate_user!
  before_action :user_sub_role
  before_action :find_user, only: %i[edit show destroy]
  before_action :load_resources, only: %i[show edit]
  before_action :update_without_password, only: %i[update]

  def index
    @q = User.where(role: @user_sub_role).ransack(params[:q])
    @users = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(params[:limit])
    export_csv(@users) if params[:export_csv].present?
  end

  def new
    @user = User.new
    @personal_detail = @user.build_personal_detail
    @personal_detail.contact_details.build
    @personal_detail.work_details.build
    @personal_detail.study_details.build
  end

  def create
    @user = User.new(user_params)
    @user.update(created_by: current_user.id)
    if @user.save
      flash[:notice] = 'User cerated successfully.'
      redirect_to root_path
    else
      flash.now[:alert] = 'User cannot be create.'
      render 'new'
    end
  end

  def edit; end

  def load_resources
    @personal_detail = @user.personal_detail
    @personal_detail = @user.build_personal_detail if @personal_detail.blank?
    @contact_details = @personal_detail.contact_details
    @personal_detail.contact_details.build if @contact_details.blank?
    @work_details = @personal_detail.work_details
    @personal_detail.work_details.build if @work_details.blank?
    @study_details = @personal_detail.study_details
    @personal_detail.study_details.build if @study_details.blank?
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User updated successfully.'
      redirect_to root_path
    else
      render 'show'
    end
  end

  def show; end

  def destroy
    @user.destroy

    redirect_to root_path
  end

  def import
    if @csv.present?
      @csv.delete('id')
      @csv.delete('encrypted_password')
      @csv.delete('created_at')
      @csv.delete('updated_at')
      csv_create_records(@csv)
      flash[:notice] = 'File Upload Successful!'
    end
    redirect_to root_path
  end

  def bulk_method
    redirect_to root_path
  end

  def archive
    @q = User.only_deleted.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(params[:limit])
  end

  def restore
    redirect_to root_path
  end

  def profile; end

  def export_csv(users)
    users = users.where(selected: true) if params[:selected]
    request.format = 'csv'
    respond_to do |format|
      format.csv { send_data users.to_csv, filename: "users-#{Date.today}.csv" }
    end
  end

  private

  def user_sub_role
    @user_sub_role = if current_user.role_super_admin?
                       'admin'
                     elsif current_user.role_admin?
                       'staff'
                     end
  end

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user)
          .permit(:email, :password, :password_confirmation, :role, :created_by, :profile_image,
                  personal_detail_attributes:
                  [:id, :first_name, :last_name, :dob, :gender,
                   { contact_details_attributes:
                   %i[id phone_number email street_address city province country zip _destroy],
                     work_details_attributes:
                   %i[id company_name position city description currently_working from to _destroy],
                     study_details_attributes:
                   %i[id school degree format description from to _destroy] }])
  end

  def update_without_password
    return unless params[:user][:password].blank? || params[:user][:password_confirmation].blank?

    params[:user].delete(:password)
    params[:user].delete(:password_confirmation)
  end

  def csv_create_records(csv)
    csv.each do |row|
      user = User.with_deleted.create_with(email: row['email'], password: 'Sample',
                                           password_confirmation: 'Sample', role: 'staff')
                 .find_or_create_by(email: row['email'])
      flash[:alert] = "#{user.errors.full_messages} at ID: #{user.id} , Try again " unless update_user(user, row)
    end
  end

  def update_user(user, row)
    user.update(row.to_hash)
  end
end

app/views/users/edit.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
    <h1>Settings</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="<%= home_path %>">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="<%= users_path %>">Settings</a>
        </li>
        <li class="breadcrumb-item active">
            <span class="active">Edit</span>
        </li>
    </ol>
</div>
<!-- End Main Content Header -->
<div class="row">
    <div class="col-xl-12">
        <div class="card mb-30">
            <div class="card-body">
                <div class="card-header">
                    <h5 class="card-title">Edit</h5>
                </div>

                <%= form_for(@user, url: user_path) do |f| %>
                    <%= render 'form', f: f %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Users</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= settings_path %>">Settings</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Users</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->
<div class="alert alert-dismissible fade show text-white jquery-selected-alert d-none " style="position: fixed; width:93%; z-index:99999;" role="alert"></div>
<div class="row">
  <div class="col-xl-12">
    <div class="card mb-30">
      <div class="card-body">
        <div class="card-header">
          <a href="/users/new" class="btn btn-primary float-right">Create</a>
          <span class='mr-1 float-right'>
            <%= form_tag import_users_path, multipart: true, method: :post do %>
              <%= file_field_tag :file, class: 'd-none import-file' %>
              <button type='button' class='btn btn-outline-success import-btn'>Import</button>
              <%= submit_tag "Import", class: 'd-none import-submit' %>
            <% end %>
          </span>
          <div class="mr-1 float-right dropdown">
            <button class="btn btn-outline-primary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Export
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to 'Export All', users_path(all: true, format: :csv, export_csv: true), class: 'dropdown-item' %>
              <%= link_to 'Export Selected', users_path(selected: true, format: :csv, export_csv: true), class: 'dropdown-item' %>
            </div>
          </div>
          <div class='mr-1 float-right'>
            <%= link_to 'Archives', archive_users_path, class: 'btn btn-outline-info' %>
          </div>
          <h5 class="card-title"><%= @user_sub_role&.capitalize %> Data</h5>
        </div>
        <%= search_form_for @q, url: users_path, method: :get do |f| %>
          <div class='row'>
            <div class="col-md-1"><br>
              <button class="btn btn-outline-info" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 42px;">
                Bulk
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target='#archive-modal'>Archive</a>
              </div>
            </div>
            <div class="col-md-2"><br>
              <%= f.search_field :email_cont, class:"form-control", placeholder:"Search in email" %>
            </div>
            <div class='col-1 offset-8'>
              <label for="inputState">Per Page</label>
              <%= select_tag :limit, options_for_select([5, 10, 15, 20], selected: params[:limit] || 10), id: 'change_per_page', class: 'form-control' %>
              <button type="submit" id="per_page_submit" hidden="hidden"></button>
            </div>
          </div><br>
        <% end %>
        <%= form_with url: bulk_method_users_path, method: :post do |f| %>
          <div class="table-responsive">
            <table class="table m-0 table-hover">
              <thead>
                <tr>
                  <th>
                    <div class='row' style='max-width: 65px'>
                      <div class='col-6 p-0'>
                        <div class="custom-control custom-switch">
                          <input type="checkbox" class="selectSwitchAll" id="selectSwitchAll" style= 'width:25px; height:25px;' onclick="bulk_update_selected('/bulk_update_selected', '<%= @users&.first&.class&.name %>', event)">
                          <label for="selectSwitchAll"></label>
                        </div>
                      </div>
                    </div>
                  </th>
                  <th>Profile</th>
                  <th>Email</th>
                  <th class="text-center">Role</th>
                  <th class="text-center">Action</th>
                </tr>
              </thead>
              <tbody>
                <% @users.each.with_index(1) do |user, index| %>
                  <tr>
                    <td>
                      <div class='row' style='max-width: 65px'>
                        <div class='col-6 p-0'>
                          <div class="custom-control custom-switch">
                            <input type="checkbox" class="selectSwitch" name="select-switch" style= 'width:25px; height:25px;' id="<%=user.id%>" <%= user.selected? ? 'checked': ''%> onclick="update_selected('/update_selected', '<%= user.class.name %>', event)">
                            <label for="<%=user.id%>"></label>
                          </div>
                        </div>
                      </div>
                    </td>
                    <td>
                      <% if  user.profile_image.attached? %>
                          <%= image_tag user.profile_image.service_url, style:'width:30px; height:30px; border-radius:50%;' %>
                      <% end %>
                    </td>
                    <td><%= user.email %></td>
                    <td class="text-center"><span class="badge badge-info"><%= user.role %></span></td>
                    <td class="text-center">
                      <div class="dropdown dropleft">
                        <button class="btn btn-primary rotate" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class='lni lni-more-alt'></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="<%= user_path(user)%>">View</a>
                          <%= link_to 'Archive', user_path(user), method: 'delete', data: {confirm: "Are you sure you want to archive"}, class: "dropdown-item"%>
                        </div>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <%= f.submit '', class: 'bulk-method-delete-objects d-none'%>
        <% end %>
        <div class='float-right'>
          <%= page_entries_info @users %>
        </div><br>
        <div class="pagination justify-content-center mt-3">
          <%= paginate @users,theme: "twitter-bootstrap-4",pagination_class: "pagination-sm",nav_class: "d-inline-b" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="archive-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Are you sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want archive selected users?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger bulk-delete-objects">Confirm</button>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<!-- Main Content Header -->
<div class="main-content-header">
  <h1>Settings</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= settings_path %>">Settings</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= users_path %>">Users</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Create</span>
    </li>
  </ol>
</div>
<!-- End Main Content Header -->
<div class="row">
    <div class="col-xl-12">
        <div class="card mb-30">
            <div class="card-body">
                <div class="card-header">
                    <h5 class="card-title">Create</h5>
                </div>

                <%= form_for @user, url: user_create_users_path, method: :post do |f| %>
                    <%= render 'form', f: f %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert" id="error_explanation">
    <h5><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h5>
    <ul class='error-list'>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<!-- Main Content Header -->
<% if @user == current_user %>
  <div class="main-content-header">
    <h1>Profile</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="<%= home_path %>">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">
        <span class="active">Profile</span>
      </li>
    </ol>
  </div>
<% else %>
  <div class="main-content-header">
    <h1>Users</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="<%= home_path %>">Dashboard</a>
      </li>
      <li class="breadcrumb-item">
        <a href="<%= settings_path %>">Settings</a>
      </li>
      <li class="breadcrumb-item">
        <a href="<%= users_path %>">Users</a>
      </li>
      <li class="breadcrumb-item active">
        <span class="active">View</span>
      </li>
    </ol>
  </div>
<% end %>

<!-- End Main Content Header -->
<!-- Profile -->
<div class="row">
  <div class="col-lg-12">
    <div class="profile-header mb-30 card">
      <div class="row card-header">
        <div class="col-6">
          <h5 class="float-left">User's Details</h5>
        </div>
        <div class="col-6 text-right">
          <button class="btn btn-outline-success" data-toggle="modal" data-target="#pinChange">
            Edit Pin
          </button>
          <a type="button" class="btn btn-outline-info ml-2" data-toggle="modal" data-target="#ModalScrollable">
            Edit User
          </a>
        </div>
      </div><br>
      <div class="row">
        <div class="col-lg-12">
          <% if @user.profile_image.attached? %>
            <%= image_tag @user.profile_image&.service_url, class: 'rounded-circle', alt: 'User Image', style: 'height:80px; width:80px;' %>
          <% else %>
            <%= image_tag('user/1.jpg', class: 'rounded-circle', alt: 'User Image') %>
          <% end %>
          <h3 class="name mt-3">Name : <%= "#{@user.personal_detail.first_name} #{@user.personal_detail.last_name}" %></h3>
          <p class="mt-3">Email : <%= @user.email  %></p>
          <p class="">Role : <%= @user.role  %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <%= render "/users/show/personal_details_partial" %>
  </div>
  <div class="col-lg-3">
    <%= render "/users/show/work_details_partial" %>
  </div>
  <div class="col-lg-3">
    <%= render "/users/show/study_details_partial" %>
  </div>
  <div class="col-lg-3">
    <%= render "/users/show/contact_details_partial" %>
  </div>
</div>
<!-- End Profile -->
<div class="modal fade" id="ModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Update User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(@user, url: user_path) do |f| %>
          <%= render '/users/form_partials/basic_form_partial', f: f %>
          <div class="form-group col-12">
            <%= f.submit(@user.new_record? ? "Create" : "Update", class: 'btn btn-outline-success rounded float-right mt-2') %>
            <button type="button" class="btn btn-secondary rounded float-right mt-2 mx-2" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= form_for(@user, url: user_path) do |f| %>
  <div class="modal fade" id="pinChange" tabindex="-1" role="dialog" aria-labelledby="examplePinChangeTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Update User</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group col-12">
            <div class="form-group relative">
              <i data-feather="eye" class="icon wh-15 eye-button-pin cursor-pointer"></i>
              <%= f.label :pin %>
              <%= f.number_field :pin, autofocus: true, class: 'form-control', type: 'password', id: 'userPin', placeholder: 'Enter 4 digit PIN', maxlength: 4, minLength: 4 %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="text-right">
            <%= f.submit 'Save', class: 'btn btn-primary'%>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>