config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
    # add other controllers if needed
  }

  get '/home', to: 'home#home'
  get '/products', to: 'home#products'
  get '/dashboard', to: 'home#dashboard'
  get '/checkout', to: 'home#checkout'
  get '/cart', to: 'home#cart'
  get '/contact', to: 'home#contact'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#home'

  # Dashboard Routes
  get '/dashboard/sales', to: 'dashboards#sales', as: :dashboard_sales
  get '/dashboard/ecommerce', to: 'dashboards#ecommerce', as: :dashboard_ecommerce
  get '/dashboard/analytics', to: 'dashboards#analytics', as: :dashboard_analytics
  get '/dashboard/crm', to: 'dashboards#crm', as: :dashboard_crm
  get '/dashboard/project', to: 'dashboards#project', as: :dashboard_project
  get '/dashboard/search', to: 'dashboards#search', as: :dashboard_search

  # Discussions Routes
  get '/discussions/inbox', to: 'discussions#inbox', as: :discussions_inbox
  get '/discussions/chat', to: 'discussions#chat', as: :discussions_chat

  # Todos Routes
  get '/todos/lists', to: 'todos#lists', as: :todos_lists
  get '/todos/notes', to: 'todos#notes', as: :todos_notes

  # UI Components Routes
  get '/ui_components/ui_alerts', to: 'ui_components#ui_alerts', as: :ui_alerts
  get '/ui_components/ui_badges', to: 'ui_components#ui_badges', as: :ui_badges
  get '/ui_components/ui_buttons', to: 'ui_components#ui_buttons', as: :ui_buttons
  get '/ui_components/ui_cards', to: 'ui_components#ui_cards', as: :ui_cards
  get '/ui_components/ui_dropdowns', to: 'ui_components#ui_dropdowns', as: :ui_dropdowns
  get '/ui_components/ui_forms', to: 'ui_components#ui_forms', as: :ui_forms
  get '/ui_components/ui_list_groups', to: 'ui_components#ui_list_groups', as: :ui_list_groups
  get '/ui_components/ui_modals', to: 'ui_components#ui_modals', as: :ui_modals
  get '/ui_components/ui_progress_bars', to: 'ui_components#ui_progress_bars', as: :ui_progress_bars
  get '/ui_components/ui_tables', to: 'ui_components#ui_tables', as: :ui_tables
  get '/ui_components/ui_tabs', to: 'ui_components#ui_tabs', as: :ui_tabs
  get '/ui_components/feather_icons', to: 'ui_components#feather_icons', as: :feather_icons
  get '/ui_components/line_icons', to: 'ui_components#line_icons', as: :line_icons
  get '/ui_components/icofont_icons', to: 'ui_components#icofont_icons', as: :icofont_icons

  # Charts Routes
  get '/charts/line', to: 'charts#line', as: :charts_line
  get '/charts/area', to: 'charts#area', as: :charts_area
  get '/charts/column', to: 'charts#column', as: :charts_column
  get '/charts/bar', to: 'charts#bar', as: :charts_bar
  get '/charts/mixed', to: 'charts#mixed', as: :charts_mixed
  get '/charts/pie', to: 'charts#pie', as: :charts_pie

  # Pages Routes
  get 'pages/users_card', to: 'pages#users_card', as: :pages_users_card
  get 'pages/notifications', to: 'pages#notifications', as: :pages_notifications
  get 'pages/timeline', to: 'pages#timeline', as: :pages_timeline
  get 'pages/invoice_template', to: 'pages#invoice_template', as: :pages_invoice_template
  get 'pages/gallery', to: 'pages#gallery', as: :pages_gallery
  get 'pages/faq', to: 'pages#faq', as: :pages_faq
  get 'pages/pricing', to: 'pages#pricing', as: :pages_pricing
  get 'pages/profile', to: 'pages#profile', as: :pages_profile
  get 'pages/profile_settings', to: 'pages#profile_settings', as: :pages_profile_settings
  get 'pages/error', to: 'pages#error', as: :pages_error

  # Auth Routes
  get 'auth/signup', to: 'auth#signup', as: :auth_signup
  get 'auth/signin', to: 'auth#signin', as: :auth_signin
  get 'auth/forgot_password', to: 'auth#forgot_password', as: :auth_forgot_password

end

app/controllers/settings_controller.rb
# frozen_string_literal: true

# User setting page for available features
class SettingsController < ApplicationController

  def index
    @total_counts = {
      products_count: '100+', users_count: '100+', categories_count: '100+',
      seasons_count: '100+', extra_field_count: '100+', email_count: '100+',
      import_mapping: '100+', courier: '100+', service: '100+', mail_service_rule: '100+',
      export_mapping: '100+', customer: '100+', pick_and_pack: '100+',
      product_location_mapping: '100+', channel_forecastings: '100+', sellings: '100+',
      customized_rules: '100+', general_settings: '100+', return_reasons: '100+'
    }
  end
end

app/views/settings/index.html.erb
<div class="main-content-header">
  <h1>Settings</h1>
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= home_path %>">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">
      <span class="active">Settings</span>
    </li>
  </ol>
</div>

<div class="row">
  <div class="col-lg-4 col-sm-6">
  <%= link_to products_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Total Products</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:products_count] %></h3>
        </div>
        <div class="avatar avatar-gold">
          <i data-feather="shopping-bag"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to users_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Total Users</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:users_count] %></h3>
        </div>
        <div class="avatar avatar-purple ">
          <i data-feather="users"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to categories_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Total Product Categories</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:categories_count] %></h3>
        </div>
        <div class="avatar avatar-blue ">
          <i data-feather="briefcase"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to seasons_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Total Seasons</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:seasons_count] %></h3>
        </div>
        <div class="avatar avatar-red ">
          <i data-feather="calendar"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to extra_field_names_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Extra Fields</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:extra_field_count] %></h3>
        </div>
        <div class="avatar avatar-cyan ">
          <i data-feather="activity"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to email_templates_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Email Tempaltes</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:email_count] %></h3>
        </div>
        <div class="avatar avatar-cyan ">
          <i data-feather="dollar-sign"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to import_mappings_path(mapping_filter: 'import') do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Import/Export Mappings</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:import_mapping] +  @total_counts[:export_mapping]%></h3>
        </div>
        <div class="avatar avatar-cyan ">
          <i data-feather="trash"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

   <div class="col-lg-4 col-sm-6">
    <%= link_to couriers_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Couriers</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:courier] %></h3>
        </div>
        <div class="avatar avatar-cyan ">
          <i data-feather="trending-up"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to services_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Services</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:service] %></h3>
        </div>
        <div class="avatar avatar-cyan ">
          <i data-feather="trending-down"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to mail_service_rules_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Mail Service Rule</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:mail_service_rule] %></h3>
        </div>
        <div class="avatar avatar-cyan ">
          <i data-feather="database"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to product_locations_path do %>
    <div class="stats-card-two hover-card mb-30">
      <div class="media align-items-center justify-content-between">
        <div class="ml-0">
          <p class="mb-10 line-height-1">Product Location Mapping</p>
          <h3 class="mb-0 fs-25"><%= @total_counts[:product_location_mapping] %></h3>
        </div>
        <div class="avatar avatar-cyan ">
          <i data-feather="check-circle"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to channel_forecastings_path do %>
      <div class="stats-card-two hover-card mb-30">
        <div class="media align-items-center justify-content-between">
          <div class="ml-0">
            <p class="mb-10 line-height-1">Channel Forecasting Rule</p>
            <h3 class="mb-0 fs-25"><%= @total_counts[:channel_forecastings] %></h3>
          </div>
          <div class="avatar avatar-cyan ">
            <i data-feather="bar-chart"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to sellings_path do %>
      <div class="stats-card-two hover-card mb-30">
        <div class="media align-items-center justify-content-between">
          <div class="ml-0">
            <p class="mb-10 line-height-1">Sellings</p>
            <h3 class="mb-0 fs-25"><%= @total_counts[:sellings] %></h3>
          </div>
          <div class="avatar avatar-cyan ">
            <i data-feather="smile"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to rules_path do %>
      <div class="stats-card-two hover-card mb-30">
        <div class="media align-items-center justify-content-between">
          <div class="ml-0">
            <p class="mb-10 line-height-1">Customized Rules</p>
            <h3 class="mb-0 fs-25"><%= @total_counts[:customized_rules].to_i %></h3>
          </div>
          <div class="avatar avatar-cyan ">
            <i data-feather="paperclip"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to general_settings_path do %>
      <div class="stats-card-two hover-card mb-30">
        <div class="media align-items-center justify-content-between">
          <div class="ml-0">
            <p class="mb-10 line-height-1">General Settings</p>
            <h3 class="mb-0 fs-25"><%= @total_counts[:general_settings].to_i %></h3>
          </div>
          <div class="avatar avatar-cyan ">
            <i data-feather="eye"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to return_reasons_path do %>
      <div class="stats-card-two hover-card mb-30">
        <div class="media align-items-center justify-content-between">
          <div class="ml-0">
            <p class="mb-10 line-height-1">Return Reasons</p>
            <h3 class="mb-0 fs-25"><%= @total_counts[:return_reasons].to_i %></h3>
          </div>
          <div class="avatar avatar-cyan ">
            <i data-feather="eye"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-4 col-sm-6">
    <%= link_to printers_path do %>
      <div class="stats-card-two hover-card mb-30">
        <div class="media align-items-center justify-content-between">
          <div class="ml-0">
            <p class="mb-10 line-height-1">Printer</p>
          </div>
          <div class="avatar avatar-cyan ">
            <i data-feather="eye"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>